import json


def export_txt(data: dict, output_path: str) -> None:
    lines = []
    lines.append("=== Recon Report ===")
    lines.append("")
    lines.append(f"Target Input: {data.get('meta', {}).get('target_input', 'N/A')}")
    lines.append(f"Generated At: {data.get('meta', {}).get('generated_at', 'N/A')}")
    lines.append("")
    lines.append("=== Parsed Target ===")
    lines.append(json.dumps(data.get("target", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== DNS ===")
    lines.append(json.dumps(data.get("dns", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== WHOIS ===")
    lines.append(json.dumps(data.get("whois", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== Tech Stack ===")
    lines.append(json.dumps(data.get("tech_stack", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== VirusTotal ===")
    lines.append(json.dumps(data.get("virustotal", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== Certificate Transparency ===")
    lines.append(json.dumps(data.get("certificate_transparency", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== Passive DNS ===")
    lines.append(json.dumps(data.get("passive_dns", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== ASN Network ===")
    lines.append(json.dumps(data.get("asn_network", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== Web Assets ===")
    lines.append(json.dumps(data.get("web_assets", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== IP Scan ===")
    lines.append(json.dumps(data.get("ip_scan", {}), ensure_ascii=False, indent=2))
    lines.append("")
    lines.append("=== Service Risk ===")
    lines.append(json.dumps(data.get("service_risk", {}), ensure_ascii=False, indent=2))
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
